# Create a new user
POST http://localhost:3000/api/authentication/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "dateBirth": "2012-02-22",
  "firstname": "Keks",
  "lastname": "Smith",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/authentication/7baad56e-22c1-4fb6-b82a-b2cac6bc3ef3 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/authentication/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###
